<div class="maincontent">
    <?php
     if(isset($_GET['quanly'])){
        $tam=$_GET['quanly'];
    }else{
        $tam='';
    }if($tam=='trangchu'){
        include("main/trangchu.php");
     }elseif($tam=='tuvan'){
        include("main/tuvan.php");
     }elseif($tam=='code'){
        include("main/code.php");
     }elseif($tam=='baihoc'){
        include("main/baihoc.php");
     }elseif($tam=='monhoc'){
      include("main/noidungbh.php");
     }elseif($tam=='khoahoc'){
      include("main/khoahoc.php");
     }elseif($tam=='study'){
      include("main/noidungkh.php");
     }elseif($tam=='learn'){
      include("main/dangky.php");
     }elseif($tam=='camon'){
      include("main/camon.php");
     }elseif($tam=='timkiem'){
      include("main/timkiem.php");
     }elseif($tam=='clip'){
      include("main/clip.php");
     }elseif($tam=='blog'){
      include("main/blog.php");
     }elseif($tam=='write'){
      include("main/infoblg.php");
     }elseif($tam=='cauhoi'){
      include("main/cauhoi.php");
     }elseif($tam=='traloi'){
      include("main/traloi.php");
     }
     else {
      include("main/batdau.php");
     }
    ?>
</div>